package com.liferay.museum.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GalleryVisit service. Represents a row in the &quot;Museum_GalleryVisit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.museum.model.impl.GalleryVisitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.museum.model.impl.GalleryVisitImpl}.
 * </p>
 *
 * @author James Falkner
 * @see GalleryVisit
 * @see com.liferay.museum.model.impl.GalleryVisitImpl
 * @see com.liferay.museum.model.impl.GalleryVisitModelImpl
 * @generated
 */
public interface GalleryVisitModel extends BaseModel<GalleryVisit>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a gallery visit model instance should use the {@link GalleryVisit} interface instead.
     */

    /**
     * Returns the primary key of this gallery visit.
     *
     * @return the primary key of this gallery visit
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this gallery visit.
     *
     * @param primaryKey the primary key of this gallery visit
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the gallery visit ID of this gallery visit.
     *
     * @return the gallery visit ID of this gallery visit
     */
    public long getGalleryVisitId();

    /**
     * Sets the gallery visit ID of this gallery visit.
     *
     * @param galleryVisitId the gallery visit ID of this gallery visit
     */
    public void setGalleryVisitId(long galleryVisitId);

    /**
     * Returns the gallery name of this gallery visit.
     *
     * @return the gallery name of this gallery visit
     */
    @AutoEscape
    public String getGalleryName();

    /**
     * Sets the gallery name of this gallery visit.
     *
     * @param galleryName the gallery name of this gallery visit
     */
    public void setGalleryName(String galleryName);

    /**
     * Returns the visitor ID of this gallery visit.
     *
     * @return the visitor ID of this gallery visit
     */
    @AutoEscape
    public String getVisitorId();

    /**
     * Sets the visitor ID of this gallery visit.
     *
     * @param visitorId the visitor ID of this gallery visit
     */
    public void setVisitorId(String visitorId);

    /**
     * Returns the group ID of this gallery visit.
     *
     * @return the group ID of this gallery visit
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this gallery visit.
     *
     * @param groupId the group ID of this gallery visit
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this gallery visit.
     *
     * @return the company ID of this gallery visit
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this gallery visit.
     *
     * @param companyId the company ID of this gallery visit
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this gallery visit.
     *
     * @return the user ID of this gallery visit
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this gallery visit.
     *
     * @param userId the user ID of this gallery visit
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this gallery visit.
     *
     * @return the user uuid of this gallery visit
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this gallery visit.
     *
     * @param userUuid the user uuid of this gallery visit
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this gallery visit.
     *
     * @return the user name of this gallery visit
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this gallery visit.
     *
     * @param userName the user name of this gallery visit
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this gallery visit.
     *
     * @return the create date of this gallery visit
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this gallery visit.
     *
     * @param createDate the create date of this gallery visit
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this gallery visit.
     *
     * @return the modified date of this gallery visit
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this gallery visit.
     *
     * @param modifiedDate the modified date of this gallery visit
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(GalleryVisit galleryVisit);

    @Override
    public int hashCode();

    @Override
    public CacheModel<GalleryVisit> toCacheModel();

    @Override
    public GalleryVisit toEscapedModel();

    @Override
    public GalleryVisit toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
