package com.liferay.museum.model.impl;

import com.liferay.museum.model.GalleryVisit;
import com.liferay.museum.service.GalleryVisitLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the GalleryVisit service. Represents a row in the &quot;Museum_GalleryVisit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GalleryVisitImpl}.
 * </p>
 *
 * @author James Falkner
 * @see GalleryVisitImpl
 * @see com.liferay.museum.model.GalleryVisit
 * @generated
 */
public abstract class GalleryVisitBaseImpl extends GalleryVisitModelImpl
    implements GalleryVisit {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a gallery visit model instance should use the {@link GalleryVisit} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            GalleryVisitLocalServiceUtil.addGalleryVisit(this);
        } else {
            GalleryVisitLocalServiceUtil.updateGalleryVisit(this);
        }
    }
}
